### ISSUE TITLE
datetime - Startjahr, Endjahr

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_xform#194]
Wäre gut wenn es die Option gebe immer das aktuelle Jahr automatisch als Startjahr zu nehmen. Wobei dies auch default sein kann.

Wenn man 1980 braucht, kann man es einfach selbst definieren.

Bei Endjahr fände ich auch ein "+3"  für "Startjahr + 3 Jahre" ganz gut. 

Das jetztige default braucht man m.E. zu selten.

**Comment by dergel** [comment]
aktuelles Datum gibt es bereits.
Bei +3 meinst Du wohl eher +3 vom aktuellen Jahr.
