### ISSUE TITLE
Komma nicht als Trennzeichen verwenden in SELECT

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_xform#203]
Hi!

Gibt es eigentlich eine Möglichkeit, das Kommazeichen gefahrlos in einem Parameter-String bei einer Select-Box zu verwenden?

In meinem konkreten Fall kann man Euro-Beträge mit Dezimalstellen in einer Select-Box auswählen, ähnlich wie dieses Beispiel:

``` php
$xform->setValueField('select', array('tarif', 'Tarif', 'Bitte auswählen=0,49,90 Euro=49.90,79,90 Euro=79.90'));
```

Heraus kommen natürlich dann folgende Optionen:

```
- Bitte auswählen
- 49
- 90 Euro
- 79
- 90 Euro
```

statt

```
- Bitte auswählen
- 49,90 Euro
- 79,90 Euro
```

Hilfsweise habe ich das eingestrichene Anführungszeichen unten genommen für die Ausgabe - zufriedenstellend ist das jedoch nicht.

Wenn es dafür keine Lösung gibt, würde ich vorschlagen, in einer kommenden xform-Version optional ein Trennzeichen übergeben zu können. Oder zwei, wegen des "=".

**Comment by alexplusde** [comment]
Kann es sein, dass das in 4.14 mittlerweile anders ist?
