### ISSUE TITLE
Prio Reihenfolge  - Feld

### ISSUE THREAD

**Issue by robo-wg** [yakamara/redaxo_xform#214]
Super wäre sowas wie ein Prio-Feld, das ähnlich wie bei Kategorien oder Artikel eine Sortierung der Einträge zulässt. Also wenn man die Prio eines Eintrags ändert, dann beeinflusst das die Prio aller anderen Einträge in der Tabelle.

**Comment by olien** [comment]
**Tabellenfelder zur Anzeige** und **Tabellenfelder zur Beschränkung** scheinen mit der aktuelle xForm Version nicht zu funktionieren... *(oder ich verstehe es nicht)*

LG
Oliver

**Comment by gharlan** [comment]
Zwei Anmerkungen dazu:

* Wenn man ein Prio-Feld neu angelegt hat und danach etwas komisch ist in den vorhandenen Datensätzen, einmal einen neu speichern, und schauen, ob es danach passt
* Bei "Tabellenfelder zu Beschränkung" im Zweifel nichts auswählen (ist der Normalfall). Man muss dort nur dann etwas auswählen, wenn nicht alle Datensätze in der Tabelle eine lange Kette bilden sollen, sondern zum Beispiel jeweils eine Kette pro Kategorie o. ä..

**Comment by olien** [comment]
Hallo Gregor, 

mit dem Wissen funktioniert es dann auch :-))

Vielen Dank!
Oliver
