### ISSUE TITLE
intfromto

### ISSUE THREAD

**Issue by robo-wg** [yakamara/redaxo_xform#243]
Kann es sein, dass intfromto keinen datestamp (Zeitstempel) auslesen kann. Habs auch mit hidden fields probiert und nicht hinbekommen. In xform 4.6 hats noch funktioniert. Im HTML-Quelltext sind hidden-Filed-values und datestamp-values korrekt enthalten...
Möchte datestamp in Kombi. mit intfromto für E-Mail-Formular-Validierung einsetzen.
Danke fürs die ansonsten wieder super gelungene 4.6er xform und beste Grüße,
Robert

**Comment by robo-wg** [comment]
Sorry, bin leider kein fleißiger github-Benutzer und hab deinen Eintrag erst jetzt gesehen. Brauchst du den Formularcode noch? An welche mail-Adr. soll ich den schicken? jan.kristinus[at]yakamara.de?

LG
Robert

**Comment by dergel** [comment]
ruhig hier in das issue schreiben

**Comment by robo-wg** [comment]
Ungern, das verrät meinen Formularcode für meine E-Mail Formulare.... Und da sind ein Spamchecker und meine Mailadresse drin... Ist  jan.kristinus[at]yakamara.de dein Adresse? Dann schick ich dir den Code dorthin.

**Comment by dergel** [comment]
kein problem ..  jan.kristinus[at]yakamara.de, ja das passt

**Comment by robo-wg** [comment]
Hallo Jan,

hast du bezüglich meines Codes schon was rausfinden können? Liegts an meinem Formular?
Grüße, Robert

**Comment by dergel** [comment]
hat etwas gedauert .. aber nun konnte ich nachschauen .. der Wert wird nicht initial gesetzt, d.h. er wurde bei der validierung nicht gefunden.. deswegen habe ich eine kleine änderung gemacht.

https://github.com/yakamara/redaxo_xform/commit/5c00ce6f2ff08287a8e738bc5cf3262ad3e4cb97

ist in der nächsten version dann möglich
