### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_xform#281]
Wenn ich xform installieren möchte, bekomme ich den Fehler:
PHP Fatal error:  Class 'rex_xform' not found in ...\redaxo\include\addons\xform\plugins\manager\classes\basic\class.rex_xform_manager_searchform.inc.php on line 4
Ursache ist der Autoinstall der Plugins: https://github.com/yakamara/redaxo_xform/blob/master/install.inc.php#L24-L51
Wenn ich den auskommentiere und die Plugins dann von Hand installiere gehts

**Comment by dergel** [comment]
das sollte schon passen... Vergessen, das hier zu kommentieren
