### ISSUE TITLE
getXFormFieldsByType() missing!

### ISSUE THREAD

**Issue by gupi** [yakamara/redaxo_xform#288]
Das Community Addon ruft in "/redaxo/addons/community/plugins/auth/pages/index.inc.php" diese Funktion auf.
Anscheinend ist diese aber noch gar nicht vorhanden.

Gunter

**Comment by dergel** [comment]
neueste community kommt damit klar

**Comment by gupi** [comment]
Großartig,
Danke, hab’s kurz angetestet - sieht sehr gut aus!

LG
Gunter
