### ISSUE TITLE
Datensatz suchen funktioniert nicht ...

### ISSUE THREAD

**Issue by mbodon** [yakamara/redaxo_xform#290]
Hallo, wenn ich in einer Tabelle bin und dort in einem Feld (text) suche erscheinen keine Ergebnisse ... leider ... ist das ein Problem nur bei mir oder auch bei jemand anderes?

**Comment by mbodon** [comment]
ach ja ... hier noch ein paar Infos ... REDAXO: 4.6.1, PHP: 5.6.0, MySQL: 5.6.19, XForm: 4.12

**Comment by mbodon** [comment]
sorry wollte es nicht CLOSE stellen

**Comment by dergel** [comment]
wie suchst du ? MIt Wildcard ? "*name*" ?

**Comment by mbodon** [comment]
Danke für den Tipp mit * ... damit funktioniert's ... wenn ich aber nur z.B. bei Name "Max" suche findet er den Datensatz " Max Müller" nicht ... Ist das ein Feature oder Bug ;-)

**Comment by mbodon** [comment]
Kannst natürlich das Isue CLOSE stellen wenn es so funktioniert ... wäre halt komfortabler wenn die Suche von sich aus automatisch ein Wildcard jeweils vor und nach dem Suchbegriff einfügt.... (nicht alle meiner Redaxo-User kennen sich mit Wildcards aus)

**Comment by dergel** [comment]
ist ein Feature sorry.. eventuell packen wir noch eine Info dazu.. Aber es soll so sein.. Gerade bei großen Tabellen ist das hilfreich wenn man mal vorne mal hinten Wildcards oder eben nicht setzen kann. deswegen close ..
