### ISSUE TITLE
Google Geo Plugin

### ISSUE THREAD

**Issue by mbodon** [yakamara/redaxo_xform#291]
Hallo, der Button "Google Geotagging" funktioniert bei mir leider nicht ... javascript wird ausgeführt aber der ajax request in Form_geo_updates liefert nix. Woran kann das liegen? An mir oder am Plugin? oder an der Zeile 10 table_field.inc.php ? dort liefert mir $table = rex_xform_manager_table::get($table_name); nur ein leeres [] zurück... was es eigentlich nicht sollte...

**Comment by mbodon** [comment]
ach ja ... hier noch ein paar Infos ... REDAXO: 4.6.1, PHP: 5.6.0, MySQL: 5.6.19, XForm & Geo-Plugin
Version: 4.12

**Comment by dergel** [comment]
das sollte nun passen (aktuelle github) version..
