### ISSUE TITLE
Case Sensitivity in Suchfeld Table Manager Übersichten

### ISSUE THREAD

**Issue by FfdE** [yakamara/redaxo_xform#297]
In einem Text-Feld in einer Table Manager Tabelle scheint die Suche Case Sensitive zu sein. Um "Swisscom AG" zu finden, muss genau dieser Begriff eingetippt werden. "swisscom" oder "Swisscom" bringt 0 Resultate. da wir unsere Adressen darüber verwaltetn, finden wir so unsere Bezugspersonen nicht mehr, von denen wir die Personennamen oder Firmennamen nicht mehr genau wissen.

**Comment by dergel** [comment]
Wir haben nun Wildcards eingeführt .. Heisst .. "*swisscom*" suchen.. das sollte dann klappen, oder ?

**Comment by FfdE** [comment]
im nachnamen-feld bei uns, also einem anderen textfeld klappts wie gehabt und gewünscht. nur im ersten textfeld eben nicht.

ich denke wildcards ist das, was wir bruachen ja






> Am 04.05.2015 um 12:54 schrieb Jan Kristinus <notifications@github.com>:
> 
> Wir haben nun Wildcards eingeführt .. Heisst .. "swisscom" suchen.. das sollte dann klappen, oder ?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yakamara/redaxo_xform/issues/297#issuecomment-98676379>.
> 



* * * * * * * * * * * * * * * * * * * * * * *

Schon Mitglied des Vereins Filme für die Erde? Unsere Mitglieder unterstützen nicht nur unsere Arbeit, sie sind auch Teil unseres Botschafter-Netzwerks. Wir verschicken Mitgliedern mindestens dreimal im Jahr DVDs zu, die dann weitergegeben werden können.

So funktionierts... <http://filmefuerdieerde.ch/mitgliedschaft>

* * * * * * * * * * * * * * * * * * * * * * *

Filme für die Erde
Kai Pulfer, Leitung
Steinberggasse 54
CH-8400 Winterthur --> Map <http://map.search.ch/winterthur/steinberggasse-54>
- - - 
Skype: kaipulfer 
- - -
+41 (0)52 202 25 53
+41 (0)77 420 63 69
- - - 
mail@filmefuerdieerde.ch <mailto:mail@filmefuerdieerde.ch>
- - -
www.FILMEfuerdieERDE.org <http://www.filmefuerdieerde.ch/>
- - -
social:
Facebook <http://www.facebook.com/pages/Filme-fur-die-Erde/19910436655> | YouTube <http://www.youtube.com/profile_play_list?user=FilmefuerdieErde> | Myspace <http://www.myspace.com/filmefuerdieerde>  | Flickr <http://www.flickr.com/photos/41557479@N07/> | Twitter <http://www.twitter.com/filmefurdieerde> | Google + <https://plus.google.com/100180442109169455928/posts> | Xing <https://www.xing.com/profiles/Kai_Pulfer>

**Comment by dergel** [comment]
das heisst nun ist alles gut ? oder klappt das bei einem bestimmten feld nicht ?

**Comment by FfdE** [comment]
beim ersten feld klappts ganz sicher NICHT, ev. bei anderen auch nicht

kann es sein, dass ich das was falsch im phpmyadmin drin habe oder so? (kollateration oder wie diese dinge heissen)



> Am 04.05.2015 um 14:40 schrieb Jan Kristinus <notifications@github.com>:
> 
> das heisst nun ist alles gut ? oder klappt das bei einem bestimmten feld nicht ?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yakamara/redaxo_xform/issues/297#issuecomment-98696340>.
> 



* * * * * * * * * * * * * * * * * * * * * * *

Schon Mitglied des Vereins Filme für die Erde? Unsere Mitglieder unterstützen nicht nur unsere Arbeit, sie sind auch Teil unseres Botschafter-Netzwerks. Wir verschicken Mitgliedern mindestens dreimal im Jahr DVDs zu, die dann weitergegeben werden können.

So funktionierts... <http://filmefuerdieerde.ch/mitgliedschaft>

* * * * * * * * * * * * * * * * * * * * * * *

Filme für die Erde
Kai Pulfer, Leitung
Steinberggasse 54
CH-8400 Winterthur --> Map <http://map.search.ch/winterthur/steinberggasse-54>
- - - 
Skype: kaipulfer 
- - -
+41 (0)52 202 25 53
+41 (0)77 420 63 69
- - - 
mail@filmefuerdieerde.ch <mailto:mail@filmefuerdieerde.ch>
- - -
www.FILMEfuerdieERDE.org <http://www.filmefuerdieerde.ch/>
- - -
social:
Facebook <http://www.facebook.com/pages/Filme-fur-die-Erde/19910436655> | YouTube <http://www.youtube.com/profile_play_list?user=FilmefuerdieErde> | Myspace <http://www.myspace.com/filmefuerdieerde>  | Flickr <http://www.flickr.com/photos/41557479@N07/> | Twitter <http://www.twitter.com/filmefurdieerde> | Google + <https://plus.google.com/100180442109169455928/posts> | Xing <https://www.xing.com/profiles/Kai_Pulfer>

**Comment by dergel** [comment]
und das erste Feld ist ein "normales" Textfeld ?

**Comment by FfdE** [comment]
ja ist ein normales textfeld
















> Am 04.05.2015 um 14:54 schrieb Jan Kristinus <notifications@github.com>:
> 
> und das erste Feld ist ein "normales" Textfeld ?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yakamara/redaxo_xform/issues/297#issuecomment-98698756>.
> 



* * * * * * * * * * * * * * * * * * * * * * *

Schon Mitglied des Vereins Filme für die Erde? Unsere Mitglieder unterstützen nicht nur unsere Arbeit, sie sind auch Teil unseres Botschafter-Netzwerks. Wir verschicken Mitgliedern mindestens dreimal im Jahr DVDs zu, die dann weitergegeben werden können.

So funktionierts... <http://filmefuerdieerde.ch/mitgliedschaft>

* * * * * * * * * * * * * * * * * * * * * * *

Filme für die Erde
Kai Pulfer, Leitung
Steinberggasse 54
CH-8400 Winterthur --> Map <http://map.search.ch/winterthur/steinberggasse-54>
- - - 
Skype: kaipulfer 
- - -
+41 (0)52 202 25 53
+41 (0)77 420 63 69
- - - 
mail@filmefuerdieerde.ch <mailto:mail@filmefuerdieerde.ch>
- - -
www.FILMEfuerdieERDE.org <http://www.filmefuerdieerde.ch/>
- - -
social:
Facebook <http://www.facebook.com/pages/Filme-fur-die-Erde/19910436655> | YouTube <http://www.youtube.com/profile_play_list?user=FilmefuerdieErde> | Myspace <http://www.myspace.com/filmefuerdieerde>  | Flickr <http://www.flickr.com/photos/41557479@N07/> | Twitter <http://www.twitter.com/filmefurdieerde> | Google + <https://plus.google.com/100180442109169455928/posts> | Xing <https://www.xing.com/profiles/Kai_Pulfer>

**Comment by dergel** [comment]
kann ich leider nicht nachvollziehen.. habe eben ein Textfeld angelegt und die Suche gestartet. Und auch nachher noch mehrere Textfelder angelegt. Überall konnte ich suchen und mit den Wildcards arbeiten

**Comment by gharlan** [comment]
> kann es sein, dass ich das was falsch im phpmyadmin drin habe oder so? (kollateration oder wie diese dinge heissen)

Welche Kollation hat denn die entsprechende Spalte?

**Comment by FfdE** [comment]
ich würde sagen utf8_general_ci


> Am 04.05.2015 um 15:58 schrieb Gregor Harlan <notifications@github.com>:
> 
> kann es sein, dass ich das was falsch im phpmyadmin drin habe oder so? (kollateration oder wie diese dinge heissen)
> 
> Welche Kollation hat denn die entsprechende Spalte?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yakamara/redaxo_xform/issues/297#issuecomment-98714047>.
> 



* * * * * * * * * * * * * * * * * * * * * * *

Schon Mitglied des Vereins Filme für die Erde? Unsere Mitglieder unterstützen nicht nur unsere Arbeit, sie sind auch Teil unseres Botschafter-Netzwerks. Wir verschicken Mitgliedern mindestens dreimal im Jahr DVDs zu, die dann weitergegeben werden können.

So funktionierts... <http://filmefuerdieerde.ch/mitgliedschaft>

* * * * * * * * * * * * * * * * * * * * * * *

Filme für die Erde
Kai Pulfer, Leitung
Steinberggasse 54
CH-8400 Winterthur --> Map <http://map.search.ch/winterthur/steinberggasse-54>
- - - 
Skype: kaipulfer 
- - -
+41 (0)52 202 25 53
+41 (0)77 420 63 69
- - - 
mail@filmefuerdieerde.ch <mailto:mail@filmefuerdieerde.ch>
- - -
www.FILMEfuerdieERDE.org <http://www.filmefuerdieerde.ch/>
- - -
social:
Facebook <http://www.facebook.com/pages/Filme-fur-die-Erde/19910436655> | YouTube <http://www.youtube.com/profile_play_list?user=FilmefuerdieErde> | Myspace <http://www.myspace.com/filmefuerdieerde>  | Flickr <http://www.flickr.com/photos/41557479@N07/> | Twitter <http://www.twitter.com/filmefurdieerde> | Google + <https://plus.google.com/100180442109169455928/posts> | Xing <https://www.xing.com/profiles/Kai_Pulfer>

**Comment by FfdE** [comment]
hmm, idee was wir machen können? wir finden unsere partner so nicht mehr, ausser wir wissen vor- oder nachname


> Am 04.05.2015 um 15:55 schrieb Jan Kristinus <notifications@github.com>:
> 
> kann ich leider nicht nachvollziehen.. habe eben ein Textfeld angelegt und die Suche gestartet. Und auch nachher noch mehrere Textfelder angelegt. Überall konnte ich suchen und mit den Wildcards arbeiten
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yakamara/redaxo_xform/issues/297#issuecomment-98712415>.
> 



* * * * * * * * * * * * * * * * * * * * * * *

Schon Mitglied des Vereins Filme für die Erde? Unsere Mitglieder unterstützen nicht nur unsere Arbeit, sie sind auch Teil unseres Botschafter-Netzwerks. Wir verschicken Mitgliedern mindestens dreimal im Jahr DVDs zu, die dann weitergegeben werden können.

So funktionierts... <http://filmefuerdieerde.ch/mitgliedschaft>

* * * * * * * * * * * * * * * * * * * * * * *

Filme für die Erde
Kai Pulfer, Leitung
Steinberggasse 54
CH-8400 Winterthur --> Map <http://map.search.ch/winterthur/steinberggasse-54>
- - - 
Skype: kaipulfer 
- - -
+41 (0)52 202 25 53
+41 (0)77 420 63 69
- - - 
mail@filmefuerdieerde.ch <mailto:mail@filmefuerdieerde.ch>
- - -
www.FILMEfuerdieERDE.org <http://www.filmefuerdieerde.ch/>
- - -
social:
Facebook <http://www.facebook.com/pages/Filme-fur-die-Erde/19910436655> | YouTube <http://www.youtube.com/profile_play_list?user=FilmefuerdieErde> | Myspace <http://www.myspace.com/filmefuerdieerde>  | Flickr <http://www.flickr.com/photos/41557479@N07/> | Twitter <http://www.twitter.com/filmefurdieerde> | Google + <https://plus.google.com/100180442109169455928/posts> | Xing <https://www.xing.com/profiles/Kai_Pulfer>

**Comment by FfdE** [comment]
Ich habs also mal mit Sternchen (*) versucht (war mir nicht klar bis anhin)


swiss* bringt alle möglichen Einträge mit Swisscom, somit super

Etwas wie „Die Werke“ ist schon schwieriger. „die*“ bringt Resultate. „werke *“ oder „*werke“ nix.

Ist das vielleicht normal?
 
Insofern wärs kein Bug, konnte früher einfach mehr/anders als heute?



> Am 04.05.2015 um 15:55 schrieb Jan Kristinus <notifications@github.com>:
> 
> kann ich leider nicht nachvollziehen.. habe eben ein Textfeld angelegt und die Suche gestartet. Und auch nachher noch mehrere Textfelder angelegt. Überall konnte ich suchen und mit den Wildcards arbeiten
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yakamara/redaxo_xform/issues/297#issuecomment-98712415>.
> 



* * * * * * * * * * * * * * * * * * * * * * *

Schon Mitglied des Vereins Filme für die Erde? Unsere Mitglieder unterstützen nicht nur unsere Arbeit, sie sind auch Teil unseres Botschafter-Netzwerks. Wir verschicken Mitgliedern mindestens dreimal im Jahr DVDs zu, die dann weitergegeben werden können.

So funktionierts... <http://filmefuerdieerde.ch/mitgliedschaft>

* * * * * * * * * * * * * * * * * * * * * * *

Filme für die Erde
Kai Pulfer, Leitung
Steinberggasse 54
CH-8400 Winterthur --> Map <http://map.search.ch/winterthur/steinberggasse-54>
- - - 
Skype: kaipulfer 
- - -
+41 (0)52 202 25 53
+41 (0)77 420 63 69
- - - 
mail@filmefuerdieerde.ch <mailto:mail@filmefuerdieerde.ch>
- - -
www.FILMEfuerdieERDE.org <http://www.filmefuerdieerde.ch/>
- - -
social:
Facebook <http://www.facebook.com/pages/Filme-fur-die-Erde/19910436655> | YouTube <http://www.youtube.com/profile_play_list?user=FilmefuerdieErde> | Myspace <http://www.myspace.com/filmefuerdieerde>  | Flickr <http://www.flickr.com/photos/41557479@N07/> | Twitter <http://www.twitter.com/filmefurdieerde> | Google + <https://plus.google.com/100180442109169455928/posts> | Xing <https://www.xing.com/profiles/Kai_Pulfer>
