### ISSUE TITLE
Suche : manche Felder fehlen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_xform#302]
siehe http://www.redaxo.org/de/forum/bugs-f31/xform-tablemanager-select-feld-nicht-bei-suchen-t20465.html

**Comment by dergel** [comment]
select und select_sql sind nn drin .. 

https://github.com/yakamara/redaxo_xform/commit/7c99ae319679fe4892b7f321c14daab5a9215910

andere felder bitte einzeln als issues anlegen.. vor allem erstmal nur die wichtigsten.
