### ISSUE TITLE
Update von Community-User geht nicht

### ISSUE THREAD

**Issue by tito-tema** [yakamara/redaxo_xform#305]
xForm 4.12: Wenn man in der Tabelle "Community User" einen User editiert und anschließend speichern will erhält man die Fehlermeldung "Diese E-Mail existiert bereits".
Zur Info hier die wichtigsten GET-Parameter, die übergeben werden:
&page=xform
&subpage=manager
&tripage=data_edit
&table_name=rex_com_user
&data_id=1
&func=edit

Entweder wird ein INSERT anstelle eines UPDATE abgesetzt oder es gibt ein Problem mit dem unique-Feld email.

**Comment by dergel** [comment]
bei beiden hast du die aktuellste version ? und auch ein reinstall gemacht ? dann ist das immernch so ? .. und user existiert wirklich noch nicht und email ist ausgefüllt ?

**Comment by tito-tema** [comment]
Alsoder Installer sagt mir, dass keine neuen Versionen verfügbar sind. xForm ist Version 4.12 und Community 4.7.2. Auch nach reinstall (erst xForm dann Community) ist das Ergebnis das gleiche:  Fehlermeldung "Diese E-Mail existiert bereits".
Und der User existiert bereits - will ihn ja aktualisieren. Und eben diese Aktualisierung klemmt.

**Comment by dergel** [comment]
ok dann anders.. kannst du dir die den aktuellen github Stand herunterladen und es dann mit den reinstall etc Sachen nochmal probieren ?

**Comment by tito-tema** [comment]
Hab jetzt mal xForm und Community von hier runtergeladen, auf dem Server ausgetauscht und ein reinstall gemacht. Das Ergebniss ist das Selbe: Ein Community-User ist nicht mehr editierbar. :-(

**Comment by dergel** [comment]
arghh.. letzter weg... du gibst mir den zugang .. email hast du ja von mir ..

**Comment by dergel** [comment]
dnke für den zugang .. das Problem ist ein anderes.. Du hast 2 User mit der gleichen E-Mail.. Deswegen akzeptiert er Änderungen an einem User nicht, da er diese doppelten E-Mails als einen Fehler interpretiert und verlangt, dass nun eine neue eingetragen werden soll.. Ist im Prinzip richtig.. Nur verwunderlich, dass 2 gleiche E-Mail drin sind.. Eventuell durch einen Import.. Das issue ist demnach aber erledigt :) ..

**Comment by tito-tema** [comment]
Oh mann ... da kann man sich ja nur vor die Stirn hauen. Wird wohl an der Hitze liegen ;-)
Und du hast recht: einen Zugang hatte ich angelegt und der zweite ist durch einen Import des Kunden in die DB gekommen. Die Fehlermeldung hat mich dann auf's Glatteis geführt - wo ich mich derzeit gerne aufhalten würde ;-)
Vielen Dank für den frischen Blick auf das Problem, was eigentlich keines war.
