### ISSUE TITLE
Manager: Suche über Select Feld

### ISSUE THREAD

**Issue by chip75** [yakamara/redaxo_xform#315]
führt zu einer Fehlerhaften Auswahl wenn man eine Option 0 defniert hat.

Select Feld
Defintion: available=0,reserved=1,booked=2
Bei der Suche wird dann immer "available" markiert. Dies führt zu irreführenden Ergebnissen.

**Comment by gharlan** [comment]
Und wenn man es abwählt und sucht, ist es trotzdem wieder ausgewählt.
