### ISSUE TITLE
Table Manager - datestamp 0:immer / 1:wenn leer wird ignoriert

### ISSUE THREAD

**Issue by darwin26** [yakamara/redaxo_xform#318]
xForm / Table Manager
Beim UPDATE eines Datensatzes wird "datestamp" immer neu gesetzt, obwohl 1:wenn leer 
gesetzt wurde.

**Comment by gharlan** [comment]
Das habe ich schon korrigiert, aber ich glaube danach wurde noch keine neue Version rausgebracht.

Probiere mal diesen Fix: https://github.com/yakamara/redaxo_xform/commit/6d2193f0d89025438a896bf3abb978514254b324

**Comment by darwin26** [comment]
hi.. fix funzt. danke ;)
