### ISSUE TITLE
CSS Fehler Table Manger

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_xform#325]
Siehe Bild
![xform](https://cloud.githubusercontent.com/assets/330516/10040262/51090f5a-61da-11e5-8d7d-c9ed41633c83.png)

**Comment by tbaddade** [comment]
Passiert das nach einem Update via Installer? Hast du einen reinstall gemacht?

**Comment by olien** [comment]
Update via Installer: Ja.
Ein Reinstall behebt den Fehler. Danke.
