### ISSUE TITLE
Feld-Beschreibungen verbessern

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_xform#331]
Im Moment sind die Feld-Beschreibungen beim Table-Manager m.E. nicht immer eindeutig, konsistent und verständlich.

Bsp: 
"Hiermit kann man SQL Abfragen als Checkboxliste nutzen"
"Hiermit kann man Verknüpfungen zu anderen Tabellen setzen"
"hiermit kann man Bereiche in der Verwaltung erstellen."
vs.
"Datums Eingabe"
"Ein PHP Code"
"Uhrzeitfeld Eingabe"

oder auch fehlerhafte Beschreibungen:
radio: "Ein Selectfeld mit festen Definitionen"
submits: "Ein einfaches Textfeld als Eingabe"

Ich habe mal versucht, die Feldbeschreibungen neu zu texten:
http://www.cheatography.com/alexplus/cheat-sheets/redaxo-xform-table-manager/

Feedback erwünscht.

**Comment by AWqxKAWERbXo** [comment]
Kommt für xform ja nicht mehr ;)
